version: '3'

name: eav
services:
 database:
  container_name: postgresql
  build:
      context: ./pg/
      dockerfile: Dockerfile
  ports:
    - '5433:5432'
  env_file:
    - './.env'
  restart: unless-stopped