version: '3'

services:
 database:
  container_name: postgresql
  image: 'bitnami/postgresql'
  ports:
    - '5433:5432'
  env_file:
    - './database.env'
  volumes:
    - ./code:/code
  restart: unless-stopped