version: '3'

services:
  database:
    container_name: postgresql
    image: 'bitnami/postgresql'
    ports:
      - '5433:5432'
    env_file:
      - './.env'
    restart: unless-stopped
  
  pgsql:
    container_name: pgsql
    build:
      context: ./pgsql
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - './.env'
    restart: no
    depends_on:
      - database

